cut_names = {
    "cut":"",
    "scifi_tracks_us":"One track in TKU",
    "scifi_fiducial_us":"TKU fiducial volume",
    "chi2_us":"TKU $\chi^2/dof$",
    "scifi_tracks_ds":"One track in TKD",
    "scifi_fiducial_ds":"TKD fiducial volume",
    "chi2_ds":"TKD $\chi^2/dof$",
    "tof01":"$t_{ToF1} - t_{ToF0}$",
    "p_tot_us":"TKU momentum",
    "p_tot_ds":"TKD momentum",
    "tof_0_sp":"One space point in ToF0",
    "tof_1_sp":"One space point in ToF1",
    "tof_2_sp":"One space point in ToF2",
    "upstream_aperture_cut":"Diffuser aperture cut",
    "downstream_aperture_cut":"Cooling channel aperture cut",
    "delta_tof01":"Extrapolated $t_{ToF0}$ - Reconstructed $t_{ToF0}$",
    "delta_tof12":"Extrapolated $t_{ToF2}$ - Reconstructed $t_{ToF2}$", #extrapolatedtof12 compared to recon tof12
    "global_through_tof0":"Successful extrapolation to ToF0",
    "global_through_tof2":"Successful extrapolation to ToF2",
    "global_through_tkd_tp":"Successful extrapolation to TKD",
    "mc_muon_us":"Monte Carlo muon in TKU",
    "mc_stations_us":"Truth registered in all TKU stations",
    "mc_scifi_fiducial_us":"Truth stayed within TKU fiducial volume",
    "mc_muon_ds":"Monte Carlo muon in TKD",
    "mc_stations_ds":"Truth passed through all TKD stations",
    "mc_scifi_fiducial_ds":"Truth stayed within TKD fiducial volume",
    ### samples ###
    "upstream_cut":"Upstream Sample",
    "downstream_cut":"Downstream Sample",
    "extrapolation_cut":"Extrapolation Sample",
    "mc_true_us_cut":"Upstream MC True Sample",
    "mc_true_ds_cut":"Downstream MC True Sample",
    "all events":"All Events",
}
max_length = max([len(name) for name in cut_names.values() if type(name) == type("")])